FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# install netcat for port check
RUN apk add --no-cache netcat-openbsd

COPY . .

# ensure entrypoint exists at ./entrypoint.sh (relative to build context)
RUN chmod +x /app/entrypoint.sh

CMD [ "sh", "-c", "/app/entrypoint.sh" ]