version: "3.9"
services:
    mongo:
        image: mongo:7
        container_name: mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    postgres:
        image: postgres:15-alpine
        container_name: postgres
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
            POSTGRES_DB: finai_db
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis_data:/data

volumes:
    mongo_data:
    pgdata:
    redis_data:
